version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=ouKoh0quae9ahv0
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=ouKoh0quae9ahv0
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:10.4.13
    environment:
      - MYSQL_ROOT_PASSWORD=ouKoh0quae9ahv0
    restart: unless-stopped
    volumes:
      - /home/tim/ipam/database:/var/lib/mysql

volumes:
  phpipam-db-data:
  phpipam-logo: