apiVersion: v1
kind: PersistentVolume
metadata:
 name: ipam-database
 labels:
   type: nfs
spec:
 capacity:
  storage: 1Mi
 accessModes:
  - ReadWriteMany
 nfs:
  server: nfs-server
  path: "/ipam/database/"
  readOnly: false