apiVersion: v1
kind: Service
metadata:
  name: ipam-database
  namespace: ipam
  labels:
    name: ipam-database
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: ipam-database
  