apiVersion: v1
kind: Service
metadata:
  name: ipam
  namespace: ipam
  labels:
    app: ipam
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: web
    targetPort: 80
  selector:
    app: ipam